# Generated by Django 4.2.5 on 2024-02-19 01:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Restaurant', 'Restaurant'), ('Hotel', 'Hotel'), ('Activity', 'Activity')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('latitude', models.DecimalField(decimal_places=13, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=13, max_digits=15)),
                ('is_family_friendly', models.BooleanField()),
                ('average_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
