# Generated by Django 4.2.5 on 2024-02-19 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='reviews',
        ),
    ]
